#!/bin/bash
set -e -o pipefail
shopt -s nullglob

exec 2> >(systemd-cat -t split-browser --level-prefix=no)
for f in {,/usr/local}/etc/split-browser/disp/*.bash; do source "$f"; done
export SB_EXT_SOCKET SB_REQ_SOCKET


socat "UNIX-LISTEN:$SB_REQ_SOCKET,fork,max-children=1" STDIO &

while IFS=$'\t' read -r -a cmd; do
    case "${cmd[0]}" in
        setup)
            found=
            for dir in "${SB_FIREFOX_DIRS[@]}"; do
                if cd "$dir"; then found=$dir; break; fi
            done
            [[ $found ]]

            printf '%s\n' '' "${cmd[@]:1}" |
            cat - /[u]sr{,/local}/share/split-browser/firefox/sb.js >sb.js

            mkdir -p defaults/pref
            ln -sf /[u]sr{,/local}/share/split-browser/firefox/sb-load.js \
                   defaults/pref
        ;;
        master)
            (
                "${SB_FIREFOX[@]}" "${cmd[@]:1}" || true
                kill -9 $! $$
            ) &
        ;;
        helper)
            "${cmd[@]:1}"
        ;;
        newtab)
            socat STDIO "UNIX-CONNECT:$SB_EXT_SOCKET" <<<"${cmd[1]}"
        ;;
    esac
done >&2
